### ISSUE TITLE
Temporarily blacklist BSSIDs

### ISSUE THREAD

**Issue by rsalvaterra-zz** [rsalvaterra/Fon#1]
Sometimes, the APs can (and do) misbehave, and we'll end up in a connect/disconnect loop. Implement a temporary BSSID blacklist (using an in-memory only SQLite database?) for bad APs.

**Comment by alanthehat** [comment]
Is a linked-list smaller & faster yet simple enough to maintain?

**Comment by alanthehat** [comment]
It looks like there's one pre-written -- http://developer.android.com/reference/java/util/LinkedList.html

**Comment by rsalvaterra-zz** [comment]
I don't think so, I need a map-like structure (using the BSSID as the key) so HashMap would fit this purpose better. I must say I'm not an Android expert (I code Java for a living, though), what I really need is to figure out where (out of the application main activity/thread, we don't want potential ANRs) shall I keep the map's reference, because of the way Android manages application lifetimes. Creating a ContentProvider seemed the "right" way to do it, but it does feel very heavyweight for such a simple purpose. Ideas welcome! :)

**Comment by alanthehat** [comment]
Would calling into the Linux part of the system help?
Multi-dimensional arrays aren't horrendous in C & I would expect C++ to be easier. 
What are you storing? I was imagining a BSSID, a time & possibly a fail-code

**Comment by rsalvaterra-zz** [comment]
BSSID, timestamp and perhaps a failure code and retry count, yes. The problem isn't the data structure itself, but where to keep its reference, so it wouldn't make sense to dig any deeper, pure Java is fine.
I must take some time to think about this, try to find code examples around the web and do some tests.

**Comment by rsalvaterra-zz** [comment]
Possible bugs apart, this is done. :)
