### ISSUE TITLE
available SSIDs in LoginManager.java

### ISSUE THREAD

**Issue by alanthehat** [rsalvaterra/Fon#2]
In LoginManager.java 
I see that you are searching for 'FON_FREE_INTERNET'. 
On my Fonera's settings there is an option to change everything after 'FON_' to an arbitrary string of my choosing.

Also, I suspect my browser isn't showing me the complete BTWiFi line, but I'm not seeing BTFON or BT_Openzone\* which are now rare, but still to be found. 

Also, what would be interesting here is a separate 'rule builder' app that offers the user a choice from available SSIDs & helps her to select a login rule to match it, saving the result in a text file in the app's home directory. (This has the potential to make the LoginManager.java routine smaller & easier to maintain)

**Comment by alanthehat** [comment]
Oops, I'm rushing & I'm on a phone, sorry.
Also, I don't know my way around either github or Java.

It looks like you may have addressed the 'FON_*' problem, but it's logically connected to 'Livedoor' & I have no idea what that is. 
https://github.com/rsalvaterra/Fon/blob/42ca73c192c8e7a8de2106dc667cce93ce9df5fe/src/org/rsalvaterra/fon/login/LoginManager.java line 53

Looking at what my phone has attempted to connect to recently I find 3 instances of 'BTOpenzone-B'. These are instances of BTOpenzone\* where '*' may be null or may also be '-H' or '-M' that I've seen, there may be others.
Same file, line 41

**Comment by rsalvaterra-zz** [comment]
Hi, sorry for the delay. I changed the login procedure quite a bit in the meantime. Livedoor is dead since 2011, and I added the other Openzone SSIDs you mentioned, although I have no means to test them, since I'm in Portugal. I guess now I have an excuse for another trip to England... :) Cheers!

**Comment by alanthehat** [comment]
I understand FritzBox also offers a FON login, but I've never seen one.
There's also a 'BTFon' but I don't remember exactly how to spell it & I haven't seen it in a year or more. 
Enjoy your trip to England :-)
Perhaps a trip to Spain to visit FON would be useful?

**Comment by alanthehat** [comment]
as I commented on 04bd61e just now
BTWiFi-with-FON & BTWifi-with-FON are both current in the Uk (difference is capitalization of the "F" in "WiFi")

**Comment by rsalvaterra-zz** [comment]
Oh, great. Why doesn't BT keep it consistent, like everybody else? :P Will fix, thanks for reporting.
